style = "blue"
indent = 4
margin = 180
always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
import_to_using = false
pipe_to_function_call = false
short_to_long_function_def = false 
long_to_short_function_def = false
always_use_return = false
whitespace_in_kwargs = true
annotate_untyped_fields_with_any = false 
format_docstrings = false
conditional_to_if = true
trailing_comma = false
indent_submodule = false
align_assignment = true
align_struct_field = true
align_conditional = true
align_pair_arrow = true
align_matrix = false
join_lines_based_on_source = false
separate_kwargs_with_semicolon = false
surround_whereop_typeparameters = true
ignore = [ "docs" ]